force-app/main/default/objects/Plant_Information_Master__mdt/Plant_Information_Master__mdt.object-meta.xml
<CustomObject>
    <label>Plant Information Master</label>
    <pluralLabel>Plant Information Masters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Plant_Information_Master__mdt/fields/Plant_Type__c.field-meta.xml
<CustomField>
    <fullName>Plant_Type__c</fullName>
    <label>Plant Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indoor</fullName>
                <default>true</default>
                <label>Indoor</label>
            </value>
            <value>
                <fullName>Outdoor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApexUseCase10.cls
public class ApexUseCase10 {
    public static string checkPlantType(string plantName){
        string plantType = 'Not Specified';
        List<Plant_Information_Master__mdt> plantRecords =[Select id, MasterLabel, Plant_Type__c from Plant_Information_Master__mdt];
        for(Plant_Information_Master__mdt pRecords: plantRecords){
            if(pRecords.MasterLabel == plantName){
                return pRecords.Plant_Type__c;
            }
        }
        return plantType;
    }
        

}